name: Checks

on: push

jobs:
  test-lint:
    name: Test and Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
